Update README

diff --git a/template/{{.input_root_dir}}/.azure/devops-pipelines/deploy-cicd.yml.tmpl b/template/{{.input_root_dir}}/.azure/devops-pipelines/deploy-cicd.yml.tmpl
--- a/template/{{.input_root_dir}}/.azure/devops-pipelines/deploy-cicd.yml.tmpl
+++ b/template/{{.input_root_dir}}/.azure/devops-pipelines/deploy-cicd.yml.tmpl
@@ -33,9 +33,20 @@ jobs:
         databricks version
       displayName: 'Get Databricks CLI version'
 
+    # Install jq
+    - script: |
+        sudo apt-get install jq
+      displayName: 'Install jq'
+
     # Unzip Bundle and Append Parameters to Input JSON
     - script: |
         tar -xzvf cicd.tar.gz
+        INPUT_CLOUD_1=$(jq -r '.input_cloud' cicd_params.json)
+        INPUT_CLOUD_2=$(jq -r '.input_cloud' {{`${{ parameters.ProjectName }}`}}/project_params.json)
+        if [ "$INPUT_CLOUD_1" != "$INPUT_CLOUD_2" ]; then
+          echo "Error: CICD cloud '$INPUT_CLOUD_1' does not match project cloud '$INPUT_CLOUD_2'"
+          exit 1
+        fi
         echo "`jq '. += {"input_project_name":"{{`${{ parameters.ProjectName }}`}}"}' cicd_params.json`" > cicd_params.json
         echo "`jq -s '.[0] + .[1]' cicd_params.json {{`${{ parameters.ProjectName }}`}}/project_params.json`" > cicd_params.json
       displayName: 'Extract CICD Bundle and Update Parameters'        
