Apply comments

diff --git a/template/{{.input_root_dir}}/.github/workflows/deploy-cicd.yml.tmpl b/template/{{.input_root_dir}}/.github/workflows/deploy-cicd.yml.tmpl
--- a/template/{{.input_root_dir}}/.github/workflows/deploy-cicd.yml.tmpl
+++ b/template/{{.input_root_dir}}/.github/workflows/deploy-cicd.yml.tmpl
@@ -21,19 +21,27 @@ env:
 
 jobs:
   cicd:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           ref: {{`${{ github.event.pull_request.head.sha || github.sha }}`}}
           token: {{`${{ secrets.WORKFLOW_TOKEN }}`}}
       - uses: databricks/setup-cli@{{template `cli_version` .}}
+      - name: Install jq
+        run: sudo apt-get install jq
       - name: Unzip Bundle and Append Parameters to Input JSON
         id: unzip
         run: |
           tar -xzvf cicd.tar.gz
+          INPUT_CLOUD_1=$(jq -r '.input_cloud' cicd_params.json)
+          INPUT_CLOUD_2=$(jq -r '.input_cloud' {{`${{ github.event.inputs.project_name }}`}}/project_params.json.json)
+          if [ "$INPUT_CLOUD_1" != "$INPUT_CLOUD_2" ]; then
+            echo "Error: CICD cloud '$INPUT_CLOUD_1' does not match project cloud '$INPUT_CLOUD_2'"
+            exit 1
+          fi
           echo "`jq '. += {"input_project_name":"{{`${{ github.event.inputs.project_name }}`}}"}' cicd_params.json`" > cicd_params.json
-          echo "`jq -s '.[0] + .[1]' cicd_params.json {{`${{ github.event.inputs.project_name }}`}}/fs_param.json`" > cicd_params.json
+          echo "`jq -s '.[0] + .[1]' cicd_params.json {{`${{ github.event.inputs.project_name }}`}}/project_params.json`" > cicd_params.json
       - name: Update databricks.yml
         id: update
         run: |
